### ISSUE TITLE
Could not subscribe to webhook

### ISSUE THREAD

**Issue by ol3gart** [RickRedSix/twitter-webhook-boilerplate-python#1]
Hello.
Trying to subscribe on twitter webhook by "python create-webhook.py" with my tokens,
 but have this error on print(r.text):

> {"errors":[{"code":200,"message":"Forbidden."}]}

what's wrong?

**Comment by andypiper** [comment]
Has your app been whitelisted for access to the Account Activity API?

**Comment by ol3gart** [comment]
Yes, not have not a  whitelist

**Comment by RickRedSix** [comment]
Hey @ol3gart, if you haven't got access to the AA API Beta, you can apply here: 

https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/overview

Without that access, you wont be able to use any of these scripts.

**Comment by unnobtainium** [comment]
hey @RickRedSix I have environments setup on https://developer.twitter.com/en/account/environments
Under 'Account Activity APISandbox' I have setup 'Dev environment label' as 'jj' and selected the app of which token I am using but still I am getting {"errors":[{"code":200,"message":"Forbidden."}]}
