### ISSUE TITLE
Error on subscribe account

### ISSUE THREAD

**Issue by ol3gart** [RickRedSix/twitter-webhook-boilerplate-python#2]
Hello.
Got this error on subscribe account with my credentials from create_webhook
`{"errors":[{"code":34,"message":"Sorry, that page does not exist."}]}`

**Comment by RickRedSix** [comment]
Hey @ol3gart, 

You won't be able to access this endpoint until you get access to the beta. You can apply for it here:

https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/overview

Without that access, you wont be able to use any of these scripts.
