### ISSUE TITLE
Response: {"errors":[{"code":34,"message":"Sorry, that page does not exist."}]}

### ISSUE THREAD

**Issue by unnobtainium** [RickRedSix/twitter-webhook-boilerplate-python#3]
Hello @RickRedSix I successfully ran create webhook but I am stuck at subscrive-account. I am getting the error message {"errors":[{"code":34,"message":"Sorry, that page does not exist."}]}.

Why is that?

**Comment by RickRedSix** [comment]
Hi @unnobtainium, just to check you are definitely replacing the ENVNAME variable with the environment name you setup here https://developer.twitter.com/en/account/environments.

Also the access_token and access_token_secret have been replaced with ones generated by the user you want to subscribe? As I ran into this issue when using the wrong access tokens.

**Comment by unnobtainium** [comment]
Thanks you. It worked.

**Comment by harrisonkanda** [comment]
> ess_token_

Hi Rick,

I'm facing this issue... what is the answer?

I have replace the ENV_NAME,  with the Environment name "dev1" which i have created in the twittwer dev account.

Also I have replace the api-keys and access_tokens/secrets appropriately (these were generated from my account as well).. 

But after doing all this .. i stiill run into this error.

How can i resolve it , please?

**Comment by RickRedSix** [comment]
Hi @harrisonkanda, 

I've just tested the example scripts and they seem to still be working for me. 

Which script is failing? The create-webhook one, or is it failing at the next step with subscribe-account?

Just to make sure, in the Twitter Dev dashboard, when you have setup the dev environment, this is linked with the same app you generated they keys for? Also the dev environment is definitely setup for 'Account Activity API / Sandbox' and not for the other Premium APIs such as 'Search Tweets: 30-Days / Sandbox'
